### PR TITLE
Create compute devices in proper location as defined in settings.tf

### PR DESCRIPTION
**Pull request by jasmas**

### CODE REVIEW

**Comment by Snergster** [comment]
good stuff..thanks

**Comment by jasmas** [comment]
I was also trying to fix virl.ini, but you or your team may need to look at it. The one in virl_cluster seems messy compared with virl_packet. Does the packet:true setting do something automagical with the network devices? I noticed virl_packet references eth interfaces in virl.ini while in the virl_cluster project it references dummynet interfaces. All the l3 addresses and subnet masks are missing from the virl.ini in virl_cluster for the compute nodes.

**Comment by Snergster** [comment]
not sure what you think needs fixing..

the packet setting makes a few alterations in various build states that follows.

if your talking about the compute nodes section of virl_packet being different…yes thats intentional because those are the defaults.

are you having issues with the cluster launcher or just trying to clean up the crud?

Ed

**Comment by jasmas** [comment]
I started out noticing that none of the computer nodes have SNAT IPs in the clustered virl.ini but then when I diffed the virl.inis of these two projects, I noticed some changes in clustered that make sense, but others not as much. 

Best,
Jason

On Thu, Jun 2, 2016 at 10:17 AM -0700, "Ed Kern" notifications@github.com wrote:

not sure what you think needs fixing..

the packet setting makes a few alterations in various build states that follows.

if your talking about the compute nodes section of virl_packet being different…yes thats intentional because those are the defaults.

are you having issues with the cluster launcher or just trying to clean up the crud?

Ed

**Pull request merged**
