### PR TITLE
virl.ini: Put all nodes on the same flat1 and flat2 networks and assign unique IPs

### PR DESCRIPTION
**Pull request by jasmas**

### CODE REVIEW

**Comment by jasmas** [comment]
Ok, finally got a chance to give virl.ini a thorough review and fix some of the problems. Sorry, it can be difficult slinging Cisco's wares by day and only getting to the fun stuff at night. lol.

**Comment by Snergster** [comment]
heh..no problem at all..I appreciate the extra set of eyes

**Comment by jasmas** [comment]
We're still missing something... every time I fire a cluster up on packet the nodes only start on virl. Also, build times on packet have started to get horrendous. Are the salt servers getting overloaded there? It took like 2 hours to build the cluster today.

**Comment by Snergster** [comment]
hey sorry for not getting back to you sooner.  i dropped in a few corrections..give it another whirl.  If it doesn't work drop me a ping and we can spin a webex so I can watch it implode on you

**Pull request merged**
